device_types:
  - type: "apple"
    mac_prefixes: ["fc:fb:fb", "ac:bc:32"]
    hostname_keywords: ["iphone", "ipad", "mac"]

  - type: "mobile"
    mac_prefixes: ["00:1a:11", "d0:37:45"]
    hostname_keywords: ["android"]

  - type: "windows"
    mac_prefixes: ["3c:5a:b4", "28:d2:44"]
    hostname_keywords: ["desktop", "win"]